I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/combat/combat screen.rpy", line 23, in script call
    pause
  File "game/combat/combat screen.rpy", line 86, in script
    label damage:
Exception: Could not find return label ('game/combat/combat screen.rpy', 1686925612, 7, 'end_translate').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/combat/combat screen.rpy", line 23, in script call
    pause
  File "game/combat/combat screen.rpy", line 86, in script
    label damage:
  File "C:\Renpy\renpy-8.0.0-sdk\renpy\ast.py", line 1762, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Renpy\renpy-8.0.0-sdk\renpy\execution.py", line 726, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label ('game/combat/combat screen.rpy', 1686925612, 7, 'end_translate').

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.0.22062402
Erasers 1.0
Fri Jun 16 22:27:40 2023
